// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GoogleLoginApiV1AuthGooglePostData, GoogleLoginApiV1AuthGooglePostErrors, GoogleLoginApiV1AuthGooglePostResponses, IndexGetData, IndexGetResponses, TokenRefreshApiV1AuthTokenRefreshPostData, TokenRefreshApiV1AuthTokenRefreshPostErrors, TokenRefreshApiV1AuthTokenRefreshPostResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Google Login
 */
export const googleLoginApiV1AuthGooglePost = <ThrowOnError extends boolean = false>(options: Options<GoogleLoginApiV1AuthGooglePostData, ThrowOnError>) => (options.client ?? client).post<GoogleLoginApiV1AuthGooglePostResponses, GoogleLoginApiV1AuthGooglePostErrors, ThrowOnError>({
    url: '/api/v1/auth/google/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Token Refresh
 */
export const tokenRefreshApiV1AuthTokenRefreshPost = <ThrowOnError extends boolean = false>(options: Options<TokenRefreshApiV1AuthTokenRefreshPostData, ThrowOnError>) => (options.client ?? client).post<TokenRefreshApiV1AuthTokenRefreshPostResponses, TokenRefreshApiV1AuthTokenRefreshPostErrors, ThrowOnError>({
    url: '/api/v1/auth/token/refresh',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Index
 */
export const indexGet = <ThrowOnError extends boolean = false>(options?: Options<IndexGetData, ThrowOnError>) => (options?.client ?? client).get<IndexGetResponses, unknown, ThrowOnError>({ url: '/', ...options });
