// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://.\\auth_service_openapi.json` | (string & {});
};

/**
 * GoogleLoginRequest
 */
export type GoogleLoginRequest = {
    /**
     * Token
     *
     * Google id token
     */
    token: string;
    /**
     * Access Token
     *
     * Google Access Token (optional)
     */
    access_token?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * TokenRefreshRequest
 */
export type TokenRefreshRequest = {
    /**
     * Refresh
     */
    refresh: string;
};

/**
 * TokenRefreshResponse
 */
export type TokenRefreshResponse = {
    /**
     * Access
     */
    access: string;
};

/**
 * TokenResponse
 */
export type TokenResponse = {
    user: UserResponse;
    /**
     * Access
     */
    access: string;
    /**
     * Refresh
     */
    refresh: string;
};

/**
 * UserResponse
 */
export type UserResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Email
     */
    email: string;
    /**
     * Picture
     */
    picture: string | null;
    /**
     * Emailverified
     */
    emailVerified: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type GoogleLoginApiV1AuthGooglePostData = {
    body: GoogleLoginRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/google/';
};

export type GoogleLoginApiV1AuthGooglePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GoogleLoginApiV1AuthGooglePostError = GoogleLoginApiV1AuthGooglePostErrors[keyof GoogleLoginApiV1AuthGooglePostErrors];

export type GoogleLoginApiV1AuthGooglePostResponses = {
    /**
     * Successful Response
     */
    200: TokenResponse;
};

export type GoogleLoginApiV1AuthGooglePostResponse = GoogleLoginApiV1AuthGooglePostResponses[keyof GoogleLoginApiV1AuthGooglePostResponses];

export type TokenRefreshApiV1AuthTokenRefreshPostData = {
    body: TokenRefreshRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/token/refresh/';
};

export type TokenRefreshApiV1AuthTokenRefreshPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TokenRefreshApiV1AuthTokenRefreshPostError = TokenRefreshApiV1AuthTokenRefreshPostErrors[keyof TokenRefreshApiV1AuthTokenRefreshPostErrors];

export type TokenRefreshApiV1AuthTokenRefreshPostResponses = {
    /**
     * Successful Response
     */
    200: TokenRefreshResponse;
};

export type TokenRefreshApiV1AuthTokenRefreshPostResponse = TokenRefreshApiV1AuthTokenRefreshPostResponses[keyof TokenRefreshApiV1AuthTokenRefreshPostResponses];

export type IndexGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type IndexGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
