// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeletePostApiV1ContentPostsContentIdDeleteData, DeletePostApiV1ContentPostsContentIdDeleteErrors, DeletePostApiV1ContentPostsContentIdDeleteResponses, GetAllPostsApiV1ContentPostsGetData, GetAllPostsApiV1ContentPostsGetErrors, GetAllPostsApiV1ContentPostsGetResponses, GetPostDetailsApiV1ContentPostsContentIdGetData, GetPostDetailsApiV1ContentPostsContentIdGetErrors, GetPostDetailsApiV1ContentPostsContentIdGetResponses, IndexGetData, IndexGetResponses, JobStatusApiV1ContentJobStatusIdGetData, JobStatusApiV1ContentJobStatusIdGetErrors, JobStatusApiV1ContentJobStatusIdGetResponses, PostsApiV1ContentPostsPostData, PostsApiV1ContentPostsPostErrors, PostsApiV1ContentPostsPostResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Job Status
 */
export const jobStatusApiV1ContentJobStatusIdGet = <ThrowOnError extends boolean = false>(options: Options<JobStatusApiV1ContentJobStatusIdGetData, ThrowOnError>) => (options.client ?? client).get<JobStatusApiV1ContentJobStatusIdGetResponses, JobStatusApiV1ContentJobStatusIdGetErrors, ThrowOnError>({ url: '/api/v1/content/job/status/{id}', ...options });

/**
 * Get All Posts
 */
export const getAllPostsApiV1ContentPostsGet = <ThrowOnError extends boolean = false>(options?: Options<GetAllPostsApiV1ContentPostsGetData, ThrowOnError>) => (options?.client ?? client).get<GetAllPostsApiV1ContentPostsGetResponses, GetAllPostsApiV1ContentPostsGetErrors, ThrowOnError>({ url: '/api/v1/content/posts', ...options });

/**
 * Posts
 */
export const postsApiV1ContentPostsPost = <ThrowOnError extends boolean = false>(options: Options<PostsApiV1ContentPostsPostData, ThrowOnError>) => (options.client ?? client).post<PostsApiV1ContentPostsPostResponses, PostsApiV1ContentPostsPostErrors, ThrowOnError>({
    url: '/api/v1/content/posts',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete Post
 */
export const deletePostApiV1ContentPostsContentIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeletePostApiV1ContentPostsContentIdDeleteData, ThrowOnError>) => (options.client ?? client).delete<DeletePostApiV1ContentPostsContentIdDeleteResponses, DeletePostApiV1ContentPostsContentIdDeleteErrors, ThrowOnError>({ url: '/api/v1/content/posts/{content_id}', ...options });

/**
 * Get Post Details
 */
export const getPostDetailsApiV1ContentPostsContentIdGet = <ThrowOnError extends boolean = false>(options: Options<GetPostDetailsApiV1ContentPostsContentIdGetData, ThrowOnError>) => (options.client ?? client).get<GetPostDetailsApiV1ContentPostsContentIdGetResponses, GetPostDetailsApiV1ContentPostsContentIdGetErrors, ThrowOnError>({ url: '/api/v1/content/posts/{content_id}', ...options });

/**
 * Index
 */
export const indexGet = <ThrowOnError extends boolean = false>(options?: Options<IndexGetData, ThrowOnError>) => (options?.client ?? client).get<IndexGetResponses, unknown, ThrowOnError>({ url: '/', ...options });
