// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://.\\content_service_openapi.json` | (string & {});
};

/**
 * ContentDetailSchema
 */
export type ContentDetailSchema = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Status
     */
    status: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Platforms
     */
    platforms: Array<string>;
    /**
     * Content
     */
    content: string;
    /**
     * Ctalink
     */
    ctaLink?: string | null;
    /**
     * Ctatype
     */
    ctaType?: string | null;
    /**
     * Language
     */
    language: string;
    /**
     * Tone
     */
    tone: string;
    /**
     * Audience
     */
    audience: string;
    /**
     * Keywords
     */
    keywords?: Array<string>;
    /**
     * Assets
     */
    assets?: Array<GeneratedAssetResponse> | null;
    /**
     * Visuals
     */
    visuals?: Array<VisualAssetResponse> | null;
    /**
     * Jobs
     */
    jobs: Array<JobResponseSchema>;
};

/**
 * ContentGenerateResponse
 */
export type ContentGenerateResponse = {
    /**
     * Content Id
     */
    content_id: string;
    /**
     * Job Id
     */
    job_id: string;
    /**
     * Status
     */
    status?: string;
};

/**
 * ContentGenerationRequest
 */
export type ContentGenerationRequest = {
    /**
     * Title
     */
    title: string;
    /**
     * Content
     *
     * The source blog or text content
     */
    content: string;
    /**
     * Ctalink
     */
    ctaLink?: string | null;
    /**
     * Language
     */
    language?: string;
    /**
     * Ctatype
     */
    ctaType?: string | null;
    /**
     * Tone
     */
    tone?: string | null;
    /**
     * Audience
     */
    audience?: string | null;
    /**
     * Content Goal
     */
    content_goal?: string | null;
    /**
     * Version
     */
    version?: number;
    /**
     * Platforms
     */
    platforms?: Array<string>;
    /**
     * Job Type
     */
    job_type: string;
};

/**
 * ContentListResponse
 */
export type ContentListResponse = {
    /**
     * Total
     */
    total: number;
    /**
     * Posts
     */
    posts: Array<ContentSummarySchema>;
};

/**
 * ContentSummarySchema
 *
 * Summarized view for lists, excludes heavy 'content' and 'assets' fields
 */
export type ContentSummarySchema = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Status
     */
    status: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Platforms
     */
    platforms?: Array<string>;
    /**
     * Jobs
     */
    jobs?: Array<JobResponseSchema>;
};

/**
 * GeneratedAssetResponse
 */
export type GeneratedAssetResponse = {
    /**
     * Platform
     *
     * The social platform (e.g., linkedin, twitter)
     */
    platform: string;
    /**
     * Version
     */
    version?: number;
    /**
     * Text
     */
    text?: string | null;
    /**
     * Meta Data
     */
    meta_data?: {
        [key: string]: unknown;
    } | null;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Id
     */
    id: string;
    /**
     * Content Post Id
     */
    content_post_id: string;
    /**
     * Job Id
     */
    job_id: string;
    /**
     * Previous Version Id
     */
    previous_version_id?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * JobResponseSchema
 */
export type UsageMetadataSchema = {
    prompt_tokens: number;
    candidates_tokens: number;
    total_tokens: number;
    "cached_tokens":number
};
export type JobResponseSchema = {
    /**
     * Id
     */
    id: string;
    /**
     * Job Type
     */
    job_type: string;
    /**
     * Progress
     */
    progress: number;
    /**
     * Status
     */
    status: string;
    /**
     * Retries
     */
    retries: number;
    /**
     * Error
     */
    error: string | null;
    ai_provider: string | null;
    usage_metadata: UsageMetadataSchema | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * VisualAssetResponse
 */
export type VisualAssetResponse = {
    /**
     * Slide Index
     *
     * The order of the slide/visual
     */
    slide_index: number;
    /**
     * Headline
     */
    headline?: string | null;
    /**
     * Subtext
     */
    subtext?: string | null;
    /**
     * Meta Data
     *
     * Metadata for image prompts or layout settings
     */
    meta_data?: {
        [key: string]: unknown;
    } | null;
    /**
     * Version
     */
    version?: number;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Platform
     */
    platform?: string;
    /**
     * Id
     */
    id: string;
    /**
     * Content Post Id
     */
    content_post_id: string;
    /**
     * Job Id
     */
    job_id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

export type JobStatusApiV1ContentJobStatusIdGetData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/content/job/status/{id}';
};

export type JobStatusApiV1ContentJobStatusIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type JobStatusApiV1ContentJobStatusIdGetError = JobStatusApiV1ContentJobStatusIdGetErrors[keyof JobStatusApiV1ContentJobStatusIdGetErrors];

export type JobStatusApiV1ContentJobStatusIdGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetAllPostsApiV1ContentPostsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number | null;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/api/v1/content/posts';
};

export type GetAllPostsApiV1ContentPostsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAllPostsApiV1ContentPostsGetError = GetAllPostsApiV1ContentPostsGetErrors[keyof GetAllPostsApiV1ContentPostsGetErrors];

export type GetAllPostsApiV1ContentPostsGetResponses = {
    /**
     * Successful Response
     */
    200: ContentListResponse;
};

export type GetAllPostsApiV1ContentPostsGetResponse = GetAllPostsApiV1ContentPostsGetResponses[keyof GetAllPostsApiV1ContentPostsGetResponses];

export type PostsApiV1ContentPostsPostData = {
    body: ContentGenerationRequest;
    path?: never;
    query?: never;
    url: '/api/v1/content/posts';
};

export type PostsApiV1ContentPostsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostsApiV1ContentPostsPostError = PostsApiV1ContentPostsPostErrors[keyof PostsApiV1ContentPostsPostErrors];

export type PostsApiV1ContentPostsPostResponses = {
    /**
     * Successful Response
     */
    200: ContentGenerateResponse;
};

export type PostsApiV1ContentPostsPostResponse = PostsApiV1ContentPostsPostResponses[keyof PostsApiV1ContentPostsPostResponses];

export type DeletePostApiV1ContentPostsContentIdDeleteData = {
    body?: never;
    path: {
        /**
         * Content Id
         */
        content_id: string;
    };
    query?: never;
    url: '/api/v1/content/posts/{content_id}';
};

export type DeletePostApiV1ContentPostsContentIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeletePostApiV1ContentPostsContentIdDeleteError = DeletePostApiV1ContentPostsContentIdDeleteErrors[keyof DeletePostApiV1ContentPostsContentIdDeleteErrors];

export type DeletePostApiV1ContentPostsContentIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetPostDetailsApiV1ContentPostsContentIdGetData = {
    body?: never;
    path: {
        /**
         * Content Id
         */
        content_id: string;
    };
    query: {
        /**
         * Job Type
         */
        job_type: string;
    };
    url: '/api/v1/content/posts/{content_id}/';
};

export type GetPostDetailsApiV1ContentPostsContentIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPostDetailsApiV1ContentPostsContentIdGetError = GetPostDetailsApiV1ContentPostsContentIdGetErrors[keyof GetPostDetailsApiV1ContentPostsContentIdGetErrors];

export type GetPostDetailsApiV1ContentPostsContentIdGetResponses = {
    /**
     * Successful Response
     */
    200: ContentDetailSchema;
};

export type GetPostDetailsApiV1ContentPostsContentIdGetResponse = GetPostDetailsApiV1ContentPostsContentIdGetResponses[keyof GetPostDetailsApiV1ContentPostsContentIdGetResponses];





export type RetryAiGenerationApiV1ContentJobJobIdPutData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: string;
    };
    query?: {
        /**
         * Job Type
         */
        job_type?: string | null;
    };
    url: '/api/v1/content/job/{job_id}/';
};

export type RetryAiGenerationApiV1ContentJobJobIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};
export type JobRetryResponse = {
    /**
     * Message
     */
    message: string;
};

export type RetryAiGenerationApiV1ContentJobJobIdPutError = RetryAiGenerationApiV1ContentJobJobIdPutErrors[keyof RetryAiGenerationApiV1ContentJobJobIdPutErrors];

export type RetryAiGenerationApiV1ContentJobJobIdPutResponses = {
    /**
     * Successful Response
     */
    200: JobRetryResponse;
};

export type RetryAiGenerationApiV1ContentJobJobIdPutResponse = RetryAiGenerationApiV1ContentJobJobIdPutResponses[keyof RetryAiGenerationApiV1ContentJobJobIdPutResponses];

export type IndexGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type IndexGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
