// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://.\\content_service_openapi.json` | (string & {});
};

/**
 * ContentDetailResponse
 */
export type ContentDetailResponse = {
    content: ContentDetailSchema;
    job?: JobDetailSchema | null;
};

/**
 * ContentDetailSchema
 */
export type ContentDetailSchema = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Status
     */
    status: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Platforms
     */
    platforms?: Array<string> | null;
    /**
     * Jobs
     */
    jobs?: Array<JobResponseSchema>;
    /**
     * Content
     */
    content: string;
    /**
     * Ctalink
     */
    ctaLink: string;
    /**
     * Ctatype
     */
    ctaType: string;
    /**
     * Language
     */
    language: string;
    /**
     * Tone
     */
    tone: string | null;
    /**
     * Audience
     */
    audience: string | null;
    /**
     * Keywords
     */
    keywords?: Array<string> | null;
};

/**
 * ContentGenerateResponse
 */
export type ContentGenerateResponse = {
    /**
     * Content Id
     */
    content_id: string;
    /**
     * Job Id
     */
    job_id: string;
    /**
     * Status
     */
    status: string;
};

/**
 * ContentGenerationRequest
 */
export type ContentGenerationRequest = {
    /**
     * Title
     */
    title: string;
    /**
     * Content
     */
    content: string;
    /**
     * Ctalink
     */
    ctaLink?: string;
    /**
     * Language
     */
    language: string;
    /**
     * Ctatype
     */
    ctaType?: string;
    /**
     * Tone
     */
    tone: string | null;
    /**
     * Audience
     */
    audience: string | null;
    /**
     * Content Goal
     */
    content_goal: string | null;
    /**
     * Version
     */
    version: number;
    /**
     * Platforms
     */
    platforms: Array<string> | null;
    /**
     * Job Type
     */
    job_type: string;
};

/**
 * ContentListResponse
 */
export type ContentListResponse = {
    /**
     * Total
     */
    total: number;
    /**
     * Posts
     */
    posts: Array<ContentSummarySchema>;
};

/**
 * ContentSummarySchema
 */
export type ContentSummarySchema = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Status
     */
    status: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Platforms
     */
    platforms: Array<string>;
    /**
     * Jobs
     */
    jobs?: Array<JobResponseSchema>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * JobDetailSchema
 */
export type JobDetailSchema = {
    /**
     * Id
     */
    id: string;
    /**
     * Job Type
     */
    job_type: string;
    /**
     * Retries
     */
    retries: number;
    /**
     * Status
     */
    status: string;
    /**
     * Percentage
     */
    percentage: number;
    /**
     * Error
     */
    error?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * JobResponseSchema
 */
export type JobResponseSchema = {
    /**
     * Id
     */
    id: string;
    /**
     * Job Type
     */
    job_type: string;
    /**
     * Progress
     */
    progress: number;
    /**
     * Status
     */
    status: string;
    /**
     * Retries
     */
    retries: number;
    /**
     * Error
     */
    error: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type JobStatusApiV1ContentJobStatusIdGetData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/content/job/status/{id}';
};

export type JobStatusApiV1ContentJobStatusIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type JobStatusApiV1ContentJobStatusIdGetError = JobStatusApiV1ContentJobStatusIdGetErrors[keyof JobStatusApiV1ContentJobStatusIdGetErrors];

export type JobStatusApiV1ContentJobStatusIdGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetAllPostsApiV1ContentPostsGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Limit
         */
        limit: number ;
        /**
         * Offset
         */
        offset: number;
    };
    url: '/api/v1/content/posts';
};

export type GetAllPostsApiV1ContentPostsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAllPostsApiV1ContentPostsGetError = GetAllPostsApiV1ContentPostsGetErrors[keyof GetAllPostsApiV1ContentPostsGetErrors];

export type GetAllPostsApiV1ContentPostsGetResponses = {
    /**
     * Successful Response
     */
    200: ContentListResponse;
};

export type GetAllPostsApiV1ContentPostsGetResponse = GetAllPostsApiV1ContentPostsGetResponses[keyof GetAllPostsApiV1ContentPostsGetResponses];

export type PostsApiV1ContentPostsPostData = {
    body: ContentGenerationRequest;
    path?: never;
    query?: never;
    url: '/api/v1/content/posts';
};

export type PostsApiV1ContentPostsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostsApiV1ContentPostsPostError = PostsApiV1ContentPostsPostErrors[keyof PostsApiV1ContentPostsPostErrors];

export type PostsApiV1ContentPostsPostResponses = {
    /**
     * Successful Response
     */
    200: ContentGenerateResponse;
};

export type PostsApiV1ContentPostsPostResponse = PostsApiV1ContentPostsPostResponses[keyof PostsApiV1ContentPostsPostResponses];

export type DeletePostApiV1ContentPostsContentIdDeleteData = {
    body?: never;
    path: {
        /**
         * Content Id
         */
        content_id: string;
    };
    query?: never;
    url: '/api/v1/content/posts/{content_id}';
};

export type DeletePostApiV1ContentPostsContentIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeletePostApiV1ContentPostsContentIdDeleteError = DeletePostApiV1ContentPostsContentIdDeleteErrors[keyof DeletePostApiV1ContentPostsContentIdDeleteErrors];

export type DeletePostApiV1ContentPostsContentIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetPostDetailsApiV1ContentPostsContentIdGetData = {
    body?: never;
    path: {
        /**
         * Content Id
         */
        content_id: string;
    };
    query: {
        /**
         * Job Type
         */
        job_type: string;
    };
    url: '/api/v1/content/posts/{content_id}';
};

export type GetPostDetailsApiV1ContentPostsContentIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPostDetailsApiV1ContentPostsContentIdGetError = GetPostDetailsApiV1ContentPostsContentIdGetErrors[keyof GetPostDetailsApiV1ContentPostsContentIdGetErrors];

export type GetPostDetailsApiV1ContentPostsContentIdGetResponses = {
    /**
     * Successful Response
     */
    200: ContentDetailResponse;
};

export type GetPostDetailsApiV1ContentPostsContentIdGetResponse = GetPostDetailsApiV1ContentPostsContentIdGetResponses[keyof GetPostDetailsApiV1ContentPostsContentIdGetResponses];

export type IndexGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type IndexGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
